name: deploy_to_host
run-name: ${{ github.actor }} is deploying
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build and Package
        run: |
          npm run build
          tar -czvf build.tar.gz build/

      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build.tar.gz
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: builds

      - name: Deploy to Server
        run: |
          scp -r build.tar.gz root@95.169.25.107:/projects -P 29146 -o "PasswordAuthentication yes" -o "PreferredAuthentications password" <<< ${{ secrets.SERVER_PASSWORD }}


